apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-example-app
  annotations:
    version: v0.0.2
    description: "This is my app revision 2"
spec:
  components:
    - name: userinfo
      type: actor
      properties:
        image: wasmcloud.azurecr.io/fake:1
      traits:
        - type: spreadscaler
          properties:
            replicas: 4
            spread:
              - name: eastcoast
                requirements:
                  zone: us-east-1
                weight: 80
              - name: westcoast
                requirements:
                  zone: us-west-1
                weight: 20
        - type: linkdef
          properties:
            target: webcap
            values:
              port: "8080"

    - name: webcap
      type: capability
      properties:
        contract: wasmcloud:httpserver
        image: wasmcloud.azurecr.io/httpserver:0.13.1
        link_name: default

    - name: ledblinky
      type: capability
      properties:
        image: wasmcloud.azurecr.io/ledblinky:0.0.1
        contract: wasmcloud:blinkenlights
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
            spread:
              - name: haslights
                requirements:
                  ledenabled: "true"
