name: e2e Tests Wadm

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: e2e
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        test: [e2e_multiple_hosts, e2e_upgrades, e2e_shared]

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install latest Rust stable toolchain
        uses: dtolnay/rust-toolchain@1ff72ee08e3cb84d84adba594e0a297990fc1ed3 # stable
        with:
          toolchain: stable
          components: clippy, rustfmt

      # Cache: rust
      - uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # v2.7.7
        with:
          key: 'ubuntu-22.04-rust-cache'

      # If the test uses a docker compose file, pre-emptively pull images used in docker compose
      - name: Pull images for test ${{ matrix.test }}
        shell: bash
        run: |
          export DOCKER_COMPOSE_FILE=tests/docker-compose-${{ matrix.test }}.yaml;
          [[ -f "$DOCKER_COMPOSE_FILE" ]] && docker compose -f $DOCKER_COMPOSE_FILE pull;

      # Run e2e tests in a matrix for efficiency
      - name: Run tests ${{ matrix.test }}
        id: test
        env:
          WADM_E2E_TEST: ${{ matrix.test }}
        run: make test-individual-e2e

      # if the previous step fails, upload logs
      - name: Upload logs for debugging
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: ${{ failure() && steps.test.outcome == 'failure' }}
        with:
          name: e2e-logs-${{ matrix.test }}
          path: ./tests/e2e_log/*
          # Be nice and only retain the logs for 7 days
          retention-days: 7
